version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: eqtl_catalogue
      POSTGRES_USER: eqtl_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./test_data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eqtl_user -d eqtl_catalogue"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: /usr/local/bin/docker-entrypoint.sh postgres -c max_wal_size=4GB

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://eqtl_user:password@db:5432/eqtl_catalogue

  data_ingester:
    build: ./data_ingestion
    command: python ingest_exons.py
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://eqtl_user:password@db:5432/eqtl_catalogue

volumes:
  db_data:
